"""create core telemedicine schema

Revision ID: e18aadb2ada7
Revises: 
Create Date: 2026-09-13 01:43:34.263516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18aadb2ada7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action_event_time', 'audit_logs', ['action', 'event_time'], unique=False)
    op.create_index('ix_audit_logs_actor_event_time', 'audit_logs', ['actor_user_id', 'event_time'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_time'), 'audit_logs', ['event_time'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'DOCTOR', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='user_status'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index('ix_users_status_role', 'users', ['status', 'role'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=150), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_accepting_patients', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_doctors_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctors')),
    sa.UniqueConstraint('license_number', name=op.f('uq_doctors_license_number')),
    sa.UniqueConstraint('user_id', name=op.f('uq_doctors_user_id'))
    )
    op.create_index('ix_doctors_accepting_verified', 'doctors', ['is_accepting_patients', 'is_verified'], unique=False)
    op.create_index(op.f('ix_doctors_is_accepting_patients'), 'doctors', ['is_accepting_patients'], unique=False)
    op.create_index(op.f('ix_doctors_is_verified'), 'doctors', ['is_verified'], unique=False)
    op.create_index(op.f('ix_doctors_specialization'), 'doctors', ['specialization'], unique=False)
    op.create_index('ix_doctors_specialization_verified', 'doctors', ['specialization', 'is_verified'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name='uq_user_profiles_user_id'),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_index(op.f('ix_user_profiles_phone'), 'user_profiles', ['phone'], unique=False)
    op.create_table('availability_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'HELD', 'BOOKED', 'CANCELLED', 'EXPIRED', name='slot_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_availability_slots_ck_availability_slots_valid_interval')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_availability_slots_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_slots')),
    sa.UniqueConstraint('doctor_id', 'starts_at', 'ends_at', name='uq_availability_slots_doctor_interval')
    )
    op.create_index('ix_availability_slots_active_start', 'availability_slots', ['is_active', 'starts_at'], unique=False)
    op.create_index(op.f('ix_availability_slots_doctor_id'), 'availability_slots', ['doctor_id'], unique=False)
    op.create_index('ix_availability_slots_doctor_status_start', 'availability_slots', ['doctor_id', 'status', 'starts_at'], unique=False)
    op.create_index(op.f('ix_availability_slots_status'), 'availability_slots', ['status'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('availability_slot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='consultation_status'), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('scheduled_end > scheduled_start', name=op.f('ck_consultations_ck_consultations_valid_schedule')),
    sa.ForeignKeyConstraint(['availability_slot_id'], ['availability_slots.id'], name=op.f('fk_consultations_availability_slot_id_availability_slots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_consultations_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_consultations_patient_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultations')),
    sa.UniqueConstraint('availability_slot_id', name=op.f('uq_consultations_availability_slot_id'))
    )
    op.create_index(op.f('ix_consultations_doctor_id'), 'consultations', ['doctor_id'], unique=False)
    op.create_index('ix_consultations_doctor_status_start', 'consultations', ['doctor_id', 'status', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_consultations_patient_id'), 'consultations', ['patient_id'], unique=False)
    op.create_index('ix_consultations_patient_status_start', 'consultations', ['patient_id', 'status', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_consultations_scheduled_start'), 'consultations', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_consultations_status'), 'consultations', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('provider', sa.Enum('STRIPE', 'RAZORPAY', 'OTHER', name='payment_provider'), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payments_ck_payments_non_negative_amount')),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_payments_consultation_id_consultations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_payments_patient_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('idempotency_key', name='uq_payments_idempotency_key'),
    sa.UniqueConstraint('provider', 'provider_payment_id', name='uq_payments_provider_payment')
    )
    op.create_index('ix_payments_consultation_status', 'payments', ['consultation_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_patient_id'), 'payments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('medicines', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('follow_up_instructions', sa.Text(), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_prescriptions_consultation_id_consultations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_prescriptions_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_prescriptions_patient_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions')),
    sa.UniqueConstraint('consultation_id', name=op.f('uq_prescriptions_consultation_id'))
    )
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index('ix_prescriptions_doctor_issued_on', 'prescriptions', ['doctor_id', 'issued_on'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index('ix_prescriptions_patient_issued_on', 'prescriptions', ['patient_id', 'issued_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prescriptions_patient_issued_on', table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index('ix_prescriptions_doctor_issued_on', table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_patient_id'), table_name='payments')
    op.drop_index('ix_payments_consultation_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_consultations_status'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_scheduled_start'), table_name='consultations')
    op.drop_index('ix_consultations_patient_status_start', table_name='consultations')
    op.drop_index(op.f('ix_consultations_patient_id'), table_name='consultations')
    op.drop_index('ix_consultations_doctor_status_start', table_name='consultations')
    op.drop_index(op.f('ix_consultations_doctor_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_availability_slots_status'), table_name='availability_slots')
    op.drop_index('ix_availability_slots_doctor_status_start', table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_doctor_id'), table_name='availability_slots')
    op.drop_index('ix_availability_slots_active_start', table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_index(op.f('ix_user_profiles_phone'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('ix_doctors_specialization_verified', table_name='doctors')
    op.drop_index(op.f('ix_doctors_specialization'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_is_verified'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_is_accepting_patients'), table_name='doctors')
    op.drop_index('ix_doctors_accepting_verified', table_name='doctors')
    op.drop_table('doctors')
    op.drop_index('ix_users_status_role', table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_time'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_event_time', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_event_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
